CREATE TABLE USER_TABLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(100),
    NAME VARCHAR(100),
    SURNAME VARCHAR(100)
);

INSERT INTO USER_TABLE (ID, USERNAME, NAME, SURNAME) VALUES
(1000001, 'mysql-user-1', 'Mark', 'Fisher'),
(1000002, 'mysql-user-2', 'Robert', 'Wiggins');